export enum Role {
  STUDENT = 'STUDENT',
  EMPLOYER = 'EMPLOYER',
  UNIVERSITY_COORDINATOR = 'UNIVERSITY_COORDINATOR',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  SYSTEM_ADMINISTRATOR = 'SYSTEM_ADMINISTRATOR',
}
